bucket         = "tfremotebackendpostgrade"
key            = "terraform-dev.tfstate"
region         = "eu-west-1"
encrypt        = true
dynamodb_table = "tf-state-lock"   # or: use_lockfile = true  (S3 native locking, TF >= 1.10)