name: tf-infra-cicd-dev

on:
  push:
    branches: ["main"]
    paths:
      - "terraform/**"
      - ".github/workflows/tf-infra-cicd-dev.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "terraform/**"
      - ".github/workflows/tf-infra-cicd-dev.yml"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: tf-dev-state
  cancel-in-progress: false

env:
  TF_VERSION: 1.10.5
  AWS_REGION: eu-west-1
  WORKING_DIR: terraform

jobs:
  plan:
    name: Terraform Plan (dev)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - run: terraform fmt -check -recursive

      - run: terraform init -backend-config=backends/dev.conf

      - run: terraform validate -no-color

      - run: terraform plan -no-color -var-file=environments/dev.tfvars

      - name: Approval
        uses: trstringer/manual-approval@v1
        timeout-minutes: 60
        with:
          secret: ${{ github.token }}
          approvers: andreea-itu
          issue-title: "Deploy Terraform Plan to dev"
          issue-body: "Please review the Terraform Plan"
          exclude-workflow-initiator-as-approver: false

  apply:
    name: Terraform Apply (dev)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: plan
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - run: terraform init -backend-config=backends/dev.conf

      - run: terraform apply -auto-approve -var-file=environments/dev.tfvars

# From main (after dev has what you want in prod)
# git checkout main
# git pull
# git checkout -b release/v1.0.0
# git push -u origin release/v1.0.0
